services:
  - type: web_service
    name: content-broadcast-frontend
    env: node
    branch: main
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    healthCheckPath: /

  - type: web_service
    name: content-broadcast-backend
    env: node
    branch: main
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    healthCheckPath: /api/health
